Atualização de Readme
prefeiturasp/SME-fila-da-creche-API pull request #2
Opened 2018-09-04 16:06 UTC by pamnovalli

2018-09-04 17:40 UTC, bplmp requested changes
Algumas observações para melhorar, especialmente corrigir as referências que hoje estão incorretamente sobre o Prato Aberto.

2018-09-04 17:40 UTC, bplmp commented on README.md
> +# Prato Aberto
Aqui deveria ser Fila da Creche, não Prato Aberto.

2018-09-04 17:40 UTC, bplmp commented on README.md
> +1.[SME- Prato Aberto](https://github.com/prefeiturasp/SME-FilaDaCreche)
Aqui deveria ser o frontend do Fila da Creche, não Prato Aberto.

2018-09-04 17:40 UTC, bplmp commented on README.md
>  ## Uso
Eu moveria isso para o topo, num estilo "quick start".

2018-09-04 17:40 UTC, bplmp commented on README.md
> +## Roadmap de tecnologia
Não sei se aqui ou em outro lugar seria legal explicar como a API e frontend interagem.

2019-01-30 14:58 UTC, pamnovalli commented on README.md
> +## Roadmap de tecnologia
@bplmp  poderia me explicar como a API e o Frontend interagem pra mim colocar na documentação como vc tinha sugerido.

2019-02-10 11:10 UTC, merged